version: '3.6'

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /path/to/host/data:/app/data
      # - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    # secrets:
    #   - password # optional but required for (1)
    environment:
      - PASSWORD=flame_password
      # - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped
    
# optional but required for Docker secrets (1)
# secrets:
#   password:
#     file: /path/to/secrets/password
